name = "Create: Adventure Awaits"
author = "CrazyGunix"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9263cef7af8bebcdf202275d27901bcd04a07b44cb6d3e8f0dcb1c1ce564b037"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
